feat: adding the react-i18next library
diegolanda/nearshore-openings pull request #1
Opened 2021-08-19 22:35 UTC by itavila

2021-08-19 22:56 UTC, diegolanda requested changes

2021-08-19 22:56 UTC, diegolanda commented on src/locales/es.json
> +{
we can delete this file, we dont need spanish

2021-08-19 22:56 UTC, diegolanda commented on src/locales/en.json
> +  "opening": {
lets use openings

2021-08-19 23:41 UTC, itavila commented on src/locales/es.json
> +{
ok

2021-08-20 20:55 UTC, diegolanda approved these changes

2021-08-20 20:57 UTC, merged